baseURL: /
title: Kilian PAQUIER

copyright: Copyright © {{ year }} Kilian PAQUIER

languageCode: fr
defaultContentLanguage: fr

module:
  imports:
    - path: gitlab.com/kilianpaquier/hugot
theme: gitlab.com/kilianpaquier/hugot

disableKinds:
  - "404"
  # - home
  # - page
  # - robotsTXT
  # - RSS
  # - section
  # - sitemap
  - taxonomy
  - term

ignoreErrors:
  - error-disable-taxonomy

params:
  favicon: /favicon.webp
  copyright:
    enabled: true

  homepage:
    overwrite: true
    url: /resume/0.2/
  
  header:
    scss:
      - scss/custom.scss