fr:
  contentDir: content
  languageName: Français
  params:
    description: Langue natale
    pre: /static/flags/fr.svg

en:
  contentDir: content
  languageName: English
  params:
    description: Professional proficiency
    pre: /static/flags/en.svg
