include:
  - project: kilianpaquier/cicd
    ref: $CICD_INDUS_BRANCH
    file:
      - pipeline/pages.yml

pages:
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  variables:
    DIST_FOLDER: public
  before_script:
    - apk add make go
    - make build
