include:
  - project: $CI_INDUS_PROJECT
    ref: $CI_INDUS_BRANCH
    file:
      - pipeline/go.yml
      - pipeline/pages.yml

pages:
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  before_script:
    - apk add make go
    - make build