include:
  - project: "$CI_INDUS_PROJECT"
    ref: $CI_INDUS_BRANCH
    file:
      - "pipelines/node.yml"
      - "pipelines/deployable-pages.yml"

building:
  variables:
    NODE_CLI_OPTS: "--base-href ./"
  before_script:
    - echo "FORMSPREE_GITLAB_URL=$FORMSPREE_GITLAB_URL" >> $CI_PROJECT_DIR/$ENV_ARTIFACT
    - echo "FORMSPREE_FR_URL=$FORMSPREE_FR_URL" >> $CI_PROJECT_DIR/$ENV_ARTIFACT 
    - echo "CAPTCHA_SITE_KEY=$CAPTCHA_SITE_KEY" >> $CI_PROJECT_DIR/$ENV_ARTIFACT

sonar-analysis:
  when: on_success

report-analysis:
  rules:
    - when: never
