baseURL = "/"
title = "Kilian PAQUIER"

copyright = "Copyright © {{ year }} Kilian PAQUIER"

languageCode = "fr"
defaultContentLanguage = "fr"

theme = [ "github.com/kilianpaquier/hugot", "github.com/dzello/reveal-hugo" ]

disableKinds = [ "404", "taxonomy", "term" ]

[module]
  [[module.imports]]
    path = "github.com/kilianpaquier/hugot"
  [[module.imports]]
    path = "github.com/dzello/reveal-hugo"

[params]
  favicon = "/favicon.webp"
  [params.copyright]
    enabled = true
  [params.homepage]
    overwrite = false # netlify takes care of doing this better in production mode
    url = "/resume/0.3/"
  [params.header]
    scss = [ "scss/custom.scss" ]

######################## Hugo Reveal ########################

  [params.reveal_hugo]
    hash = true
    highlight_theme = "github"
    history = true
    previewLinks = true
    theme = "white"
    load_default_plugins = false

    # [[params.reveal_hugo.plugins]]
    #   name = "RevealHighlight"
    #   source = "reveal-js/plugin/highlight/highlight.js"

    [[params.reveal_hugo.plugins]]
      name = "RevealMarkdown"
      source = "reveal-js/plugin/markdown/markdown.js"

    [[params.reveal_hugo.plugins]]
      name = "RevealSearch"
      source = "reveal-js/plugin/search/search.js"

    [[params.reveal_hugo.plugins]]
      name = "RevealNotes"
      source = "reveal-js/plugin/notes/notes.js"

    [[params.reveal_hugo.plugins]]
      name = "RevealMath"
      source = "reveal-js/plugin/math/math.js"

    [[params.reveal_hugo.plugins]]
      name = "RevealZoom"
      source = "reveal-js/plugin/zoom/zoom.js"

    [params.logo]
      width = "150px" # fix reveal hugo slides logo size

[outputFormats.Reveal]
  baseName = "index"
  mediaType = "text/html"
  isHTML = true

[markup.highlight]
  codeFences = true
  lineNos = true
  lineNumbersInTable = false
  style = "github-dark"

[markup.goldmark.renderer]
  unsafe = true
