[[redirects]]
  force = true
  from = "https://kilianpaquier.netlify.app/*"
  status = 301
  to = "https://kilianpaquier.com/:splat"

[[redirects]]
  force = true
  from = "/slides/:name"
  to = "/slides/:name/reveal"
  status = 301
