// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EduComponent: typeof import('./src/components/side/EduComponent.vue')['default']
    ExpComponent: typeof import('./src/components/main/ExpComponent.vue')['default']
    InterestsComponent: typeof import('./src/components/side/InterestsComponent.vue')['default']
    IntroComponent: typeof import('./src/components/IntroComponent.vue')['default']
    KListItem: typeof import('./src/components/common/KListItem.vue')['default']
    KRoundedImg: typeof import('./src/components/common/KRoundedImg.vue')['default']
    KRow: typeof import('./src/components/common/KRow.vue')['default']
    KSkill: typeof import('./src/components/common/KSkill.vue')['default']
    PrintProjectsComponent: typeof import('./src/components/side/PrintProjectsComponent.vue')['default']
    ProjectsComponent: typeof import('./src/components/main/ProjectsComponent.vue')['default']
    SocialComponent: typeof import('./src/components/SocialComponent.vue')['default']
  }
}
