// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EduComponent: typeof import('./src/components/side/EduComponent.vue')['default']
    ExpComponent: typeof import('./src/components/main/ExpComponent.vue')['default']
    InterestsComponent: typeof import('./src/components/side/InterestsComponent.vue')['default']
    IntroComponent: typeof import('./src/components/IntroComponent.vue')['default']
    KListItem: typeof import('./src/components/common/KListItem.vue')['default']
    KRoundedImg: typeof import('./src/components/common/KRoundedImg.vue')['default']
    KRow: typeof import('./src/components/common/KRow.vue')['default']
    KSkill: typeof import('./src/components/common/KSkill.vue')['default']
    PrintProjectsComponent: typeof import('./src/components/side/PrintProjectsComponent.vue')['default']
    ProjectsComponent: typeof import('./src/components/main/ProjectsComponent.vue')['default']
    SocialComponent: typeof import('./src/components/SocialComponent.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAvatar: typeof import('vuetify/lib')['VAvatar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VExpandTransition: typeof import('vuetify/lib')['VExpandTransition']
    VExpansionPanel: typeof import('vuetify/lib')['VExpansionPanel']
    VExpansionPanelContent: typeof import('vuetify/lib')['VExpansionPanelContent']
    VExpansionPanelHeader: typeof import('vuetify/lib')['VExpansionPanelHeader']
    VExpansionPanels: typeof import('vuetify/lib')['VExpansionPanels']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemAvatar: typeof import('vuetify/lib')['VListItemAvatar']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemGroup: typeof import('vuetify/lib')['VListItemGroup']
    VListItemSubtitle: typeof import('vuetify/lib')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VRow: typeof import('vuetify/lib')['VRow']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VTimeline: typeof import('vuetify/lib')['VTimeline']
    VTimelineItem: typeof import('vuetify/lib')['VTimelineItem']
    VTooltip: typeof import('vuetify/lib')['VTooltip']
    VWindow: typeof import('vuetify/lib')['VWindow']
    VWindowItem: typeof import('vuetify/lib')['VWindowItem']
  }
}
