main: []
  # - identifier: home
  #   name: Home
  #   url: /
  #   weight: 5

  # - identifier: resume
  #   name: Mon CV
  #   url: /resume/
  #   weight: 20

  # - identifier: slides
  #   name: Slides
  #   url: /slides/
  #   weight: 20