main:
  # - identifier: home
  #   name: Home
  #   url: /
  #   weight: 5

  - identifier: blog
    name: Blog
    url: /blog/
    weight: 10

  - identifier: docs
    name: Docs
    url: /docs/workspace/softwares/
    weight: 15

  - identifier: resume
    name: My Resume
    url: /resume/
    weight: 20